### ISSUE TITLE
Revisit spelling

### ISSUE THREAD

**Issue by LowPowerLab** [lukastheiler/ttn_moteino#1]
Nice article!
I noticed Moteino is mispelled in a few places and a few other words as well as some words are merged together, maybe run the whole thing through a spell check and change to **Moteino** ;-)

**Comment by lukastheiler** [comment]
fixed - my apologies!

**Comment by LowPowerLab** [comment]
Thanks, no problem, just figured that if people search the web for **moteino+the thing network** they might not find it easily.
I still see **monteino** and **monetino** in a few places.
Also I guess the repository name and sketch name are set in stone and cannot be changed now.

**Comment by lukastheiler** [comment]
I can change the sketches, but not the repository right now.

**Comment by lukastheiler** [comment]
... and renamed the repository now as well :)
